import './api-token-workspace.css'

type Principal={id:number;name:string;description:string;is_active:boolean;created_at:string;disabled_at:string|null;created_by:string}
type ApiCredential={id:number;name:string;token_prefix:string;scopes:string[];expires_at:string|null;is_active:boolean;last_used_at:string|null;created_at:string;revoked_at:string|null;created_by:string;service_principal:Principal|null}
type IssuedApiCredential=ApiCredential&{token:string;token_notice:string}
type ApiError={detail?:string}

const scopeOptions=[['accounts:read','Accounts'],['dashboard:read','Dashboard'],['resources:read','Resources'],['costs:read','Costs'],['compliance:read','Compliance'],['policies:read','Policies'],['recommendations:read','Recommendations'],['reports:read','Reports']] as const
let mountedSection:HTMLElement|null=null
let currentSecret=''
let currentSecretNotice=''

function csrfToken(){return document.cookie.split('; ').find(value=>value.startsWith('csrftoken='))?.split('=')[1]??''}
function escapeHtml(value:string):string{return value.replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]??char))}
function when(value:string|null){return value?new Date(value).toLocaleString():'Never'}
function isExpired(token:ApiCredential){return Boolean(token.expires_at&&new Date(token.expires_at).getTime()<=Date.now())}
function tokenState(token:ApiCredential){if(!token.is_active)return 'Revoked';if(isExpired(token))return 'Expired';if(token.service_principal&&!token.service_principal.is_active)return 'Principal disabled';return 'Active'}
function tokenStateClass(token:ApiCredential){const state=tokenState(token);return state==='Active'?'active':state==='Expired'?'expired':'revoked'}
async function request<T>(url:string,options:RequestInit={}):Promise<T>{const headers=new Headers(options.headers);if(options.method==='POST'){headers.set('Content-Type','application/json');headers.set('X-CSRFToken',csrfToken())}const response=await fetch(url,{credentials:'include',...options,headers});const data=await response.json().catch(()=>({})) as T&ApiError;if(!response.ok)throw new Error(data.detail??`${response.status}`);return data}
function administrationButton():HTMLButtonElement|null{return Array.from(document.querySelectorAll<HTMLButtonElement>('aside nav button')).find(button=>button.childNodes[0]?.textContent?.trim()==='Administration')??null}
function isAdministrationActive(){return administrationButton()?.classList.contains('active')??false}
function clearTransientSecret(){currentSecret='';currentSecretNotice=''}
function scopeBadges(scopes:string[]){return scopes.map(scope=>`<span class="api-token-scope">${escapeHtml(scope)}</span>`).join('')}
function scopeCheckboxes(){return scopeOptions.map(([value,label],index)=>`<label class="api-token-scope-option"><input type="checkbox" name="scopes" value="${value}" ${index===0?'checked':''}/><span>${label}</span><small>${value}</small></label>`).join('')}
function principalOptions(principals:Principal[]){return ['<option value="">Human owner (current user)</option>',...principals.filter(p=>p.is_active).map(p=>`<option value="${p.id}">${escapeHtml(p.name)}</option>`)].join('')}
function principalRows(principals:Principal[]){return principals.map(p=>`<tr><td><b>${escapeHtml(p.name)}</b><small>${escapeHtml(p.description||'No description')}</small></td><td><span class="api-token-state ${p.is_active?'active':'revoked'}">${p.is_active?'Active':'Disabled'}</span></td><td>${escapeHtml(p.created_by)}</td><td>${escapeHtml(when(p.created_at))}</td><td><button class="ghost-button compact" data-principal-toggle="${p.id}" data-principal-active="${p.is_active?'1':'0'}">${p.is_active?'Disable':'Enable'}</button></td></tr>`).join('')}
function tokenRows(tokens:ApiCredential[]){return tokens.map(token=>`<tr><td><b>${escapeHtml(token.name)}</b><small>finopser_${escapeHtml(token.token_prefix)}_…</small></td><td><span class="api-token-state ${tokenStateClass(token)}">${tokenState(token)}</span></td><td>${token.service_principal?`<b>${escapeHtml(token.service_principal.name)}</b><small>Service principal</small>`:'Human owner'}</td><td><div class="api-token-scopes">${scopeBadges(token.scopes)}</div></td><td>${token.expires_at?escapeHtml(when(token.expires_at)):'Never'}</td><td>${escapeHtml(when(token.last_used_at))}</td><td><div class="api-token-actions">${token.is_active?`<button class="ghost-button compact" data-token-rotate="${token.id}" ${token.service_principal&&!token.service_principal.is_active?'disabled':''}>Rotate</button><button class="ghost-button compact" data-token-revoke="${token.id}">Revoke</button>`:'—'}</div></td></tr>`).join('')}

function showSecret(article:HTMLElement,token:string,notice:string){const target=article.querySelector<HTMLElement>('[data-token-secret]');if(!target)return;target.innerHTML=`<div class="api-token-secret"><div><strong>Copy this token now</strong><p>${escapeHtml(notice||'Finopser will not display it again after this page state is cleared.')}</p></div><code>${escapeHtml(token)}</code><button class="ghost-button compact" data-copy-token>Copy</button><button class="link-button" data-dismiss-token>Dismiss</button></div>`;target.querySelector<HTMLButtonElement>('[data-copy-token]')?.addEventListener('click',async event=>{const button=event.currentTarget as HTMLButtonElement;try{await navigator.clipboard.writeText(token);button.textContent='Copied'}catch{button.textContent='Copy failed'}});target.querySelector<HTMLButtonElement>('[data-dismiss-token]')?.addEventListener('click',()=>{clearTransientSecret();target.replaceChildren()})}

function render(article:HTMLElement,tokens:ApiCredential[],principals:Principal[]){article.innerHTML=`<div class="api-token-head"><div><p class="eyebrow">INTEGRATIONS</p><h2>Automation identities</h2></div><span class="api-token-count">${principals.filter(p=>p.is_active).length} active principals</span></div><p class="api-token-intro">Create tenant-bound service principals for non-human read-only automation. Disabling a principal immediately blocks every credential bound to it without deleting audit history.</p><div class="api-principal-grid"><form class="api-token-form api-principal-form" data-principal-form><label>Principal name<input name="name" type="text" maxlength="120" placeholder="Example: nightly-cost-export" required/></label><label>Description<input name="description" type="text" placeholder="Purpose or owning system"/></label><button class="primary-button" type="submit">Create principal</button></form>${principals.length?`<div class="table-wrap api-token-table"><table><thead><tr><th>Principal</th><th>State</th><th>Created by</th><th>Created</th><th></th></tr></thead><tbody>${principalRows(principals)}</tbody></table></div>`:'<div class="empty">No service principals have been created for this workspace.</div>'}</div><hr class="api-token-divider"/><div class="api-token-head"><div><p class="eyebrow">CREDENTIALS</p><h2>API tokens</h2></div><span class="api-token-count">${tokens.filter(token=>token.is_active&&!isExpired(token)).length} active</span></div><p class="api-token-intro">Issue least-privilege read-only Bearer tokens to a service principal or retain the existing human-owned token workflow. Secrets are shown once and never stored in plaintext.</p><form class="api-token-form" data-token-form><label class="api-token-name">Token name<input name="name" type="text" maxlength="120" placeholder="Example: reporting-cli" required/></label><label>Identity<select name="service_principal">${principalOptions(principals)}</select></label><label class="api-token-expiration">Expires (optional)<input name="expires_at" type="datetime-local"/></label><fieldset class="api-token-scope-fieldset"><legend>Read scopes</legend><div class="api-token-scope-grid">${scopeCheckboxes()}</div></fieldset><button class="primary-button" type="submit">Issue token</button></form><div data-token-secret></div>${tokens.length?`<div class="table-wrap api-token-table"><table><thead><tr><th>Name</th><th>State</th><th>Identity</th><th>Scopes</th><th>Expires</th><th>Last used</th><th></th></tr></thead><tbody>${tokenRows(tokens)}</tbody></table></div>`:'<div class="empty">No API tokens have been issued for this workspace.</div>'}<p class="api-token-note">Bearer tokens remain limited to approved read-only API endpoints. Rotation invalidates the previous secret immediately; revocation and principal disablement take effect immediately.</p>`
 article.querySelector<HTMLFormElement>('[data-principal-form]')?.addEventListener('submit',event=>{event.preventDefault();void createPrincipal(article,event.currentTarget as HTMLFormElement)})
 article.querySelector<HTMLFormElement>('[data-token-form]')?.addEventListener('submit',event=>{event.preventDefault();void issue(article,event.currentTarget as HTMLFormElement)})
 article.querySelectorAll<HTMLButtonElement>('[data-principal-toggle]').forEach(button=>button.addEventListener('click',()=>void togglePrincipal(article,Number(button.dataset.principalToggle),button.dataset.principalActive==='1')))
 article.querySelectorAll<HTMLButtonElement>('[data-token-rotate]').forEach(button=>button.addEventListener('click',()=>void rotate(article,Number(button.dataset.tokenRotate))))
 article.querySelectorAll<HTMLButtonElement>('[data-token-revoke]').forEach(button=>button.addEventListener('click',()=>void revoke(article,Number(button.dataset.tokenRevoke))))
 if(currentSecret)showSecret(article,currentSecret,currentSecretNotice)
}

async function load(article:HTMLElement){try{const [tokens,principals]=await Promise.all([request<ApiCredential[]>('/api/integrations/tokens/'),request<Principal[]>('/api/integrations/service-principals/')]);if(article.isConnected&&isAdministrationActive())render(article,tokens,principals)}catch(error){const message=error instanceof Error?error.message:'request failed';if(message==='Manager access is required.'){article.innerHTML='<div class="api-token-head"><div><p class="eyebrow">INTEGRATIONS</p><h2>Automation identities</h2></div></div><div class="empty">Integration administration is available to workspace owners and administrators.</div>';return}article.innerHTML=`<div class="banner danger">Unable to load integration credentials (${escapeHtml(message)}).</div>`}}
async function createPrincipal(article:HTMLElement,form:HTMLFormElement){const name=(form.elements.namedItem('name') as HTMLInputElement).value.trim();const description=(form.elements.namedItem('description') as HTMLInputElement).value.trim();if(!name)return;try{await request('/api/integrations/service-principals/',{method:'POST',body:JSON.stringify({name,description})});await load(article)}catch(error){window.alert(`Unable to create service principal (${error instanceof Error?error.message:'request failed'}).`)}}
async function togglePrincipal(article:HTMLElement,id:number,isActive:boolean){const verb=isActive?'disable':'enable';if(!window.confirm(`${isActive?'Disable':'Enable'} this service principal?${isActive?' Bound automation will immediately lose access.':''}`))return;try{await request(`/api/integrations/service-principals/${id}/${verb}/`,{method:'POST',body:'{}'});await load(article)}catch(error){window.alert(`Unable to ${verb} service principal (${error instanceof Error?error.message:'request failed'}).`)}}
async function issue(article:HTMLElement,form:HTMLFormElement){const name=(form.elements.namedItem('name') as HTMLInputElement).value.trim();if(!name)return;const scopes=Array.from(form.querySelectorAll<HTMLInputElement>('input[name="scopes"]:checked')).map(input=>input.value);if(!scopes.length){window.alert('Select at least one read scope.');return}const expirationInput=form.elements.namedItem('expires_at') as HTMLInputElement;const expires_at=expirationInput.value?new Date(expirationInput.value).toISOString():null;const principalInput=form.elements.namedItem('service_principal') as HTMLSelectElement;const service_principal=principalInput.value?Number(principalInput.value):null;try{const issued=await request<IssuedApiCredential>('/api/integrations/tokens/',{method:'POST',body:JSON.stringify({name,scopes,expires_at,service_principal})});currentSecret=issued.token;currentSecretNotice=issued.token_notice;await load(article)}catch(error){window.alert(`Unable to issue token (${error instanceof Error?error.message:'request failed'}).`)}}
async function rotate(article:HTMLElement,id:number){if(!window.confirm('Rotate this API token? The current secret will stop working immediately.'))return;try{const issued=await request<IssuedApiCredential>(`/api/integrations/tokens/${id}/rotate/`,{method:'POST',body:'{}'});currentSecret=issued.token;currentSecretNotice=issued.token_notice;await load(article)}catch(error){window.alert(`Unable to rotate token (${error instanceof Error?error.message:'request failed'}).`)}}
async function revoke(article:HTMLElement,id:number){if(!window.confirm('Revoke this API token? Any automation using it will immediately lose access.'))return;try{await request(`/api/integrations/tokens/${id}/revoke/`,{method:'POST',body:'{}'});await load(article)}catch(error){window.alert(`Unable to revoke token (${error instanceof Error?error.message:'request failed'}).`)}}
function mount(){if(!isAdministrationActive()){clearTransientSecret();mountedSection=null;return}const main=document.querySelector('main');if(!main)return;let article=main.querySelector<HTMLElement>('[data-api-token-workspace]');if(!article){article=document.createElement('section');article.className='panel api-token-panel';article.dataset.apiTokenWorkspace='true';main.appendChild(article)}if(article===mountedSection&&article.dataset.apiTokenMounted==='true')return;mountedSection=article;article.dataset.apiTokenMounted='true';article.innerHTML='<h2>Automation identities</h2><div class="empty">Loading integration credentials…</div>';void load(article)}
function schedule(){window.setTimeout(mount,0)}
document.addEventListener('click',event=>{const target=event.target as HTMLElement|null;if(target?.closest('aside nav button'))schedule()})
new MutationObserver(()=>schedule()).observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['class']})
schedule()
