import React, { useEffect, useState } from 'react'
import ReactDOM from 'react-dom/client'
import './styles.css'

const nav = ['Dashboard','Organization','Accounts','Resources','Costs','Compliance','Policies','Automation','Reports','Administration']

type Dashboard = { spend:{mtd:number|string;previous_comparable:number|string;change_percent:number|string|null;currency:string}; resources:{total:number;active:number;inactive:number;by_type:{resource_type:string;count:number}[];by_account:{cloud_account:number;cloud_account__name:string;count:number}[];by_region:{region:string;count:number}[]}; top_costs:{service:{service:string;total:number|string}[];account:{cloud_account:number;cloud_account__name:string;total:number|string}[];project:{project:number|null;project__name:string|null;total:number|string}[];region:{region:string;total:number|string}[]}; accounts:{total:number;by_status:{status:string;count:number}[]}; attention:{severity:string;kind:string;title:string;detail:string;target:string}[] }
type ComplianceSummary = { frameworks:number;controls:number;findings:{open:number;excepted:number;resolved:number;by_severity:{severity:string;count:number}[]};active_exceptions:number;latest_run:null|{passed_count:number;failed_count:number;unknown_count:number;resolved_count:number;completed_at:string|null} }
type PolicySummary = { policies:{total:number;enabled:number;observe:number;recommend:number};violations:{open:number;resolved:number;by_severity:{severity:string;count:number}[]};latest_run:null|{passed_count:number;violated_count:number;unknown_count:number;resolved_count:number;completed_at:string|null} }
const money=(value:number|string|undefined)=>value===undefined?'—':`$${Number(value).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`

function App(){
 const[active,setActive]=useState('Dashboard');const[dashboard,setDashboard]=useState<Dashboard|null>(null);const[compliance,setCompliance]=useState<ComplianceSummary|null>(null);const[policies,setPolicies]=useState<PolicySummary|null>(null);const[dashboardError,setDashboardError]=useState(false)
 useEffect(()=>{fetch('/api/dashboard/',{credentials:'include'}).then(r=>r.ok?r.json():Promise.reject()).then(setDashboard).catch(()=>setDashboardError(true));fetch('/api/compliance/summary/',{credentials:'include'}).then(r=>r.ok?r.json():Promise.reject()).then(setCompliance).catch(()=>undefined);fetch('/api/policies/summary/',{credentials:'include'}).then(r=>r.ok?r.json():Promise.reject()).then(setPolicies).catch(()=>undefined)},[])
 const spendChange=dashboard?.spend.change_percent;const spendChangeText=spendChange===null||spendChange===undefined?'No comparable prior-period data':`${Number(spendChange)>=0?'+':''}${spendChange}% vs comparable prior period`;const complianceIssues=(compliance?.findings.open??0)+(compliance?.findings.excepted??0)
 return <div className="app-shell"><aside><div className="brand">finopser</div><div className="tagline">Cloud governance & FinOps</div><nav>{nav.map(item=><button onClick={()=>setActive(item)} className={active===item?'active':''} key={item}>{item}<span>{['Dashboard','Organization','Accounts','Resources','Costs','Compliance','Policies','Administration'].includes(item)?'●':'Soon'}</span></button>)}</nav></aside><main>
 {active==='Dashboard'&&<><header><div><p className="eyebrow">OPERATIONAL INTELLIGENCE</p><h1>What needs attention right now?</h1></div><div className="status"><i/>Persisted data only</div></header>{dashboardError&&<section className="panel"><h2>Dashboard data unavailable</h2><p>Sign in and verify the API is healthy. The dashboard does not make live AWS calls.</p></section>}<section className="cards"><article><span>MTD cloud spend</span><strong>{money(dashboard?.spend.mtd)}</strong><small>{spendChangeText}</small></article><article><span>Active resources</span><strong>{dashboard?.resources.active??'—'}</strong><small>{dashboard?.resources.inactive??'—'} inactive historically</small></article><article><span>Compliance findings</span><strong>{compliance?complianceIssues:'—'}</strong><small>{compliance?.findings.open??'—'} open · {compliance?.findings.excepted??'—'} excepted</small></article><article><span>Policy violations</span><strong>{policies?.violations.open??'—'}</strong><small>{policies?.policies.enabled??'—'} enabled guardrails</small></article><article><span>Operational attention</span><strong>{dashboard?.attention.length??'—'}</strong><small>Evidence-backed signals</small></article></section><section className="grid"><div className="panel"><p className="eyebrow">IMMEDIATE ATTENTION</p><h2>Prioritized signals</h2>{dashboard?(dashboard.attention.length?<ul>{dashboard.attention.map((item,index)=><li key={`${item.kind}-${index}`}><b>{item.severity.toUpperCase()} · {item.title}</b><span>{item.target}</span><small>{item.detail}</small></li>)}</ul>:<p>No current operational attention signals.</p>):<p>Loading operational signals…</p>}</div><div className="panel"><p className="eyebrow">GOVERNANCE POSTURE</p><h2>Compliance & policies</h2><ul><li><b>Open compliance findings</b><span>{compliance?.findings.open??'—'}</span></li><li><b>Open policy violations</b><span>{policies?.violations.open??'—'}</span></li><li><b>Observe policies</b><span>{policies?.policies.observe??'—'}</span></li><li><b>Recommend policies</b><span>{policies?.policies.recommend??'—'}</span></li></ul></div></section><section className="grid"><div className="panel"><h2>Resources by type</h2>{dashboard?.resources.by_type.length?<ul>{dashboard.resources.by_type.map(item=><li key={item.resource_type}><b>{item.resource_type}</b><span>{item.count}</span></li>)}</ul>:<p>No inventory data loaded.</p>}</div><div className="panel"><h2>Top services this month</h2>{dashboard?.top_costs.service.length?<ul>{dashboard.top_costs.service.map(item=><li key={item.service}><b>{item.service}</b><span>{money(item.total)}</span></li>)}</ul>:<p>No current-month cost data loaded.</p>}</div></section></>}
 {active==='Resources'&&<><header><div><p className="eyebrow">RESOURCE INVENTORY</p><h1>AWS resources</h1></div><div className="pill">READ ONLY</div></header><section className="cards"><article><span>Total inventory</span><strong>{dashboard?.resources.total??'—'}</strong></article><article><span>Active</span><strong>{dashboard?.resources.active??'—'}</strong></article><article><span>Inactive</span><strong>{dashboard?.resources.inactive??'—'}</strong></article><article><span>Types</span><strong>{dashboard?.resources.by_type.length??'—'}</strong></article></section></>}
 {active==='Costs'&&<><header><div><p className="eyebrow">FINOPS</p><h1>AWS cost visibility</h1></div><div className="pill">READ ONLY</div></header><section className="cards"><article><span>MTD spend</span><strong>{money(dashboard?.spend.mtd)}</strong></article><article><span>Prior comparable</span><strong>{money(dashboard?.spend.previous_comparable)}</strong></article><article><span>Services</span><strong>{dashboard?.top_costs.service.length??'—'}</strong></article><article><span>Regions</span><strong>{dashboard?.top_costs.region.length??'—'}</strong></article></section></>}
 {active==='Compliance'&&<><header><div><p className="eyebrow">SPRINT 7 · COMPLIANCE</p><h1>Evidence-backed compliance posture</h1></div><div className="pill">OBSERVE</div></header><section className="cards"><article><span>Frameworks</span><strong>{compliance?.frameworks??'—'}</strong></article><article><span>Controls</span><strong>{compliance?.controls??'—'}</strong></article><article><span>Open findings</span><strong>{compliance?.findings.open??'—'}</strong></article><article><span>Excepted</span><strong>{compliance?.findings.excepted??'—'}</strong></article></section></>}
 {active==='Policies'&&<><header><div><p className="eyebrow">SPRINT 8 · POLICIES & GUARDRAILS</p><h1>Scoped governance without cloud mutation</h1></div><div className="pill">OBSERVE / RECOMMEND</div></header><section className="cards"><article><span>Policies</span><strong>{policies?.policies.total??'—'}</strong><small>{policies?.policies.enabled??'—'} enabled</small></article><article><span>Observe</span><strong>{policies?.policies.observe??'—'}</strong><small>Visibility only</small></article><article><span>Recommend</span><strong>{policies?.policies.recommend??'—'}</strong><small>Recommended action</small></article><article><span>Open violations</span><strong>{policies?.violations.open??'—'}</strong><small>{policies?.violations.resolved??'—'} resolved historically</small></article></section><section className="grid"><div className="panel"><h2>Latest policy evaluation</h2>{policies?.latest_run?<ul><li><b>Passed</b><span>{policies.latest_run.passed_count}</span></li><li><b>Violations</b><span>{policies.latest_run.violated_count}</span></li><li><b>Unknown</b><span>{policies.latest_run.unknown_count}</span></li><li><b>Resolved</b><span>{policies.latest_run.resolved_count}</span></li></ul>:<p>No policy evaluation has been run yet.</p>}<p><code>POST /api/policies/evaluate/</code> evaluates persisted evidence only.</p></div><div className="panel"><h2>Initial guardrails</h2><ul><li><b>EC2 public IPv4</b><span>Observe</span></li><li><b>RDS public accessibility</b><span>Observe</span></li><li><b>RDS storage encryption</b><span>Recommend</span></li></ul><p>No policy in Sprint 8 can mutate AWS.</p></div></section></>}
 {active==='Organization'&&<><header><div><p className="eyebrow">ORGANIZATION</p><h1>Hierarchy & projects</h1></div></header><section className="panel"><h2>Organization management</h2><p>Manage organizations, recursive nodes, and projects through authenticated APIs.</p></section></>}
 {active==='Accounts'&&<><header><div><p className="eyebrow">AWS ACCOUNTS</p><h1>Account onboarding</h1></div><div className="pill">OBSERVE</div></header><section className="panel"><h2>Register, validate, then sync</h2><ul><li><b>Validate role</b><span>POST /api/cloud-accounts/&lt;id&gt;/validate/</span></li><li><b>Sync inventory</b><span>POST /api/cloud-accounts/&lt;id&gt;/sync-inventory/</span></li><li><b>Sync costs</b><span>POST /api/cloud-accounts/&lt;id&gt;/sync-costs/</span></li></ul></section></>}
 {active==='Administration'&&<><header><div><p className="eyebrow">ADMINISTRATION</p><h1>Roles & audit</h1></div></header><section className="panel"><h2>Governed operations</h2><p>Roles, audit events, syncs, compliance evaluations, exceptions, policy changes, and policy evaluations remain available through authenticated APIs.</p></section></>}
 {!['Dashboard','Organization','Accounts','Resources','Costs','Compliance','Policies','Administration'].includes(active)&&<section className="panel"><p className="eyebrow">PLANNED</p><h2>{active}</h2><p>This capability is intentionally outside the current Sprint.</p></section>}
 </main></div>
}
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>)
